from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from rt import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^error/$', views.error, name='error'),
	url(r'^login/$', views.login, name='login'),
	url(r'^actor/$', views.actor_main, name='actor_main'),
	url(r'^actor/(?P<i>\d+)/$', views.actor_info, name='actor_info'),
	url(r'^actor/(?P<i>\d+)/edit/suggest/$', views.actor_edit_suggest, name='actor_edit_suggest'),
        url(r'^actor/(?P<i>\d+)/edit/suggest/confirm/$', views.actor_edit_suggest_confirm, name='actor_edit_suggest_confirm'),
	url(r'^actor/(?P<i>\d+)/delete/$', views.actor_delete, name='actor_delete'),
	url(r'^actor/(?P<i>\d+)/delete/confirm/$', views.actor_delete_confirm, name='actor_delete_confirm'),
	url(r'^actor/add/$', views.actor_add, name='actor_add'),
	url(r'^actor/add/(?P<i>\d+)/$', views.actor_add_confirm, name='actor_add_confirm'),
	url(r'^actor/add/(?P<i>\d+)/confirm/$', views.actor_add_end, name='actor_add_end'),
	url(r'^actor/edit/$', views.actor_edit, name='actor_edit'),
        url(r'^actor/edit/(?P<i>\d+)/confirm/$', views.actor_edit_confirm, name='actor_edit_confirm'),
        url(r'^actor/edit/(?P<i>\d+)/end/$', views.actor_edit_end, name='actor_edit_end'),
	url(r'^actor/search/$', views.actor_search, name='actor_search'),
	url(r'^actor/search/result/$', views.actor_search_result, name='actor_search_result'),
	url(r'^actor_suggest/$', views.actor_suggest, name='actor_suggest'),
	url(r'^actor_suggest/confirm/$', views.actor_suggest_confirm, name='actor_suggest_confirm'),
	url(r'^help/$', views.help, name='help'),
	url(r'^movie/$', views.movie_main, name='movie_main'),
	url(r'^movie/(?P<i>\d+)/$', views.movie_info, name='movie_info'),
	url(r'^movie/(?P<i>\d+)/edit/suggest/$', views.movie_edit_suggest, name='movie_edit_suggest'),
	url(r'^movie/(?P<i>\d+)/edit/suggest/confirm/$', views.movie_edit_suggest_confirm, name='movie_edit_suggest_confirm'),
	url(r'^movie/(?P<i>\d+)/delete/$', views.movie_delete, name='movie_delete'),
	url(r'^movie/(?P<i>\d+)/delete/confirm/$', views.movie_delete_confirm, name='movie_delete_confirm'),
	url(r'^movie/(?P<i>\d+)/watchlist/$', views.movie_watchlist, name='movie_watchlist'),
	url(r'^movie/add/$', views.movie_add, name='movie_add'),
	url(r'^movie/add/(?P<i>\d+)/$', views.movie_add_confirm, name='movie_add_confirm'),
	url(r'^movie/add/(?P<i>\d+)/confirm/$', views.movie_add_end, name='movie_add_end'),
	url(r'^movie/edit/$', views.movie_edit, name='movie_edit'),
	url(r'^movie/edit/(?P<i>\d+)/confirm/$', views.movie_edit_confirm, name='movie_edit_confirm'),	
	url(r'^movie/edit/(?P<i>\d+)/end/$', views.movie_edit_end, name='movie_edit_end'),
	url(r'^movie/search/$', views.movie_search, name='movie_search'),
	url(r'^movie/search/result/$', views.movie_search_result, name='movie_search_result'),
	url(r'^movie_suggest/$', views.movie_suggest, name='movie_suggest'),
	url(r'^movie_suggest/confirm/$', views.movie_suggest_confirm, name='movie_suggest_confirm'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^news/add/$', views.news_add, name='news_add'),
	url(r'^news/add/end/$', views.news_add_end, name='news_add_end'),
	url(r'^not_implemented/$', views.not_implemented, name='not_implemented'),
	url(r'^perm_denied/$', views.perm_denied, name='perm_denied'),
	url(r'^register/$', views.register, name='register'),
	url(r'^register_confirm/$', views.register_confirm, name='register_confirm'),
	url(r'^search/$', views.navigation_search, name='navigation_search'),
	url(r'^tv/$', views.tv_main, name='tv_main'),
	url(r'^tv/(?P<i>\d+)/$', views.tv_info, name='tv_info'),
	url(r'^tv/(?P<i>\d+)/watchlist/$', views.tv_watchlist, name='tv_watchlist'),
	url(r'^tv/add/$', views.tv_add, name='tv_add'),
        url(r'^tv/add/(?P<i>\d+)/$', views.tv_add_confirm, name='tv_add_confirm'),
        url(r'^tv/add/(?P<i>\d+)/confirm/$', views.tv_add_end, name='tv_add_end'),
	url(r'^tv_suggest/$', views.tv_suggest, name='tv_suggest'),
        url(r'^tv_suggest/confirm/$', views.tv_suggest_confirm, name='tv_suggest_confirm')
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )
